### ISSUE TITLE
Only works for repositories in `C:\`

### ISSUE THREAD

**Issue by anonymous1184** [KonstantinosKol/GitHidder#1]
I've tried different things to make it work on other drives (even manually creating the entries, but simply doesn't work).

Among the many things I've tried was to create a junction point, but not even with that I could make it work for repositories on my other drives.

I have no problems with any kind of path, as long as it's on the `C:` drive. As soon as I try my `D:` (data partition), `E:` (external drive), `M:` (Network path), etc... it doesn't work.

**Comment by KonstantinosKolotouros** [comment]
Thank you a lot, for your feedback. I’m really happy that you gave me feedback for my work, and I will try to fix this serious issue, as soon as possible. I hope to be able to help me, with more information about this specific problem, if I need your guidance. Thank you again. KK From: anonymous1184Sent: Τρίτη, 28 Μαρτίου 2023 10:21 μμTo: KonstantinosKol/GitHidderCc: SubscribedSubject: [KonstantinosKol/GitHidder] Only works for repositories in `C:\` (Issue #1) I've tried different things to make it work on other drives (even manually creating the entries, but simply doesn't work).Among the many things I've tried was to create a junction point, but not even with that I could make it work for repositories on my other drives.I have no problems with any kind of path, as long as it's on the C: drive. As soon as I try my D: (data partition), E: (external drive), M: (Network path), etc... it doesn't work.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***> Χωρίς ιούς.www.avast.com

**Comment by anonymous1184** [comment]
Thanks for looking into this, I really want to use the extension as an alternative to `.env` files.

Well, I tried so many things (even manually adding the `filter` entries to the repo config and the `.gitattributes` file)... but none worked, so I'm pretty confident it is just that the extension has an error when it comes to the path.

I haven't tried with WSL, but I don't want to depend on either the path or having to do it trough `ext4` file system.

I used a pristine VSCode installation (via the portable) and created blank repos. The one in `C:\` has an error on the first attempt (`An error has occurred, try again`), then from the second attempt it works. The one in `D:\` never works.

I tried in my current installation but also on clean VMs W10 and W11 (both 22H2, latest updates).

An image is worth a thousand words, so:

![img1](https://user-images.githubusercontent.com/53758552/228583413-a7fc5dfa-8533-494d-8f15-536081a87b30.png)

BTW, this is the full error when installing the extension:

![img2](https://user-images.githubusercontent.com/53758552/228583520-f8203fc6-1241-469b-b321-9f90922b9d76.png)

The error when you try to hide text is always the same: `An error has occurred, try again`. If you close the folder and open it again, there is another error: `An error occurred while trying to identify current directory`. However, I don't see anything of note in the `Output` from `git`:

![img3](https://user-images.githubusercontent.com/53758552/228583668-3fb1b448-9428-4c89-a07c-82587ea22d69.png)

![img4](https://user-images.githubusercontent.com/53758552/228583689-44f9344b-89f8-4520-a9cf-38fa83e9223e.png)

There is other error, when opening a new window: `You need to open a project first`. I think that should only be shown when the user tries to add/remove words, rather than on window load.

**Comment by KonstantinosKolotouros** [comment]
Hello again. 

I found the problem on my code, when you have a project on a diferent disk rather than main C disk of your computer. I have fix this problem with the new version (0.0.7) of GitHidder and i have change some messages to display when the user wants to add/remove words.

I hope to be able to use the extension again, without any problem.

**Comment by anonymous1184** [comment]
Working like a charm, thanks for the fix!
